from setuptools import find_packages, setup

setup(
    name="isles26",
    version="0.1.0",
    description="ISLES'26 Ischemic Stroke Lesion Segmentation",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Vincess DONGMO",
    author_email="sodiaque806@gmail.com",
    url="https://github.com/hashirama21/isles2026-Ischemic-Stroke-Lesion-Segmentation",
    license="Apache-2.0",
    python_requires=">=3.10",
    packages=find_packages(include=["src", "src.*"]),
    install_requires=[
        "torch>=2.2.0",
        "torchvision>=0.17.0",
        "pytorch-lightning>=2.2.0",
        "monai[all]>=1.3.0",
        "torchio>=0.19.6",
        "nibabel>=5.2.0",
        "SimpleITK>=2.3.1",
        "antspyx>=0.4.2",
        "hydra-core>=1.3.2",
        "omegaconf>=2.3.0",
        "wandb>=0.16.0",
        "numpy>=1.26.0",
        "pandas>=2.2.0",
        "scikit-learn>=1.4.0",
        "scipy>=1.12.0",
        "tqdm>=4.66.0",
        "rich>=13.7.0",
        "einops>=0.7.0",
        "connected-components-3d>=3.12.0",
    ],
    extras_require={
        "dev": [
            "pytest>=8.0.0",
            "pytest-cov>=4.1.0",
            "ruff>=0.3.0",
            "mypy>=1.9.0",
            "pre-commit>=3.7.0",
            "ipykernel>=6.29.0",
            "matplotlib>=3.8.0",
            "seaborn>=0.13.0",
            "jupyterlab>=4.1.0",
        ],
        "mamba": [
            "mamba-ssm>=1.2.0",
            "causal-conv1d>=1.2.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    keywords=[
        "stroke",
        "lesion segmentation",
        "MRI",
        "deep learning",
        "nnU-Net",
        "FiLM",
        "MONAI",
        "ISLES",
        "Grand Challenge",
    ],
)